name: GitHub Actions
on: [push]
jobs:
    run-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [14.x]
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies 
          run: npm ci
        - name: Run tests
          run: npm test
        - name: Make test coverage
          run: npm run coverage
        - name: Coveralls 
          uses: coverallsapp/github-action@v2.2.3
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
